export const APPLOADED_SUCCESS = 'APPLOADED_SUCCESS';

export const UPD_KEY_VALUE = 'UPD_KEY_VALUE';

export const ISMOBILE_SUCCESS = 'ISMOBILE_SUCCESS';

export const SCREEN_SIZE = 'SCREEN_SIZE';

export const TECHNOLOGY_SUCCESS = 'TECHNOLOGY_SUCCESS';

export const INVOLVED_SUCCESS = 'INVOLVED_SUCCESS';

export const LEARN_SUCCESS = 'LEARN_SUCCESS';

export const MENTOR_SUCCESS = 'MENTOR_SUCCESS';

export const HIRE_SUCCESS = 'HIRE_SUCCESS';

export const SECTION_LIST = 'SECTION_LIST';

export const CURRENT_PATH = 'CURRENT_PATH';

export const FORMS_SUCCESS = 'FORMS_SUCCESS';

export const FORMS_OBSERVES = 'FORMS_OBSERVES';

export const VALIDATIONFORMS_SUCCESS = 'VALIDATIONFORMS_SUCCESS';
