export const APPLOADED_SUCCESS = 'APPLOADED_SUCCESS';

export const UPD_KEY_VALUE = 'UPD_KEY_VALUE';

export const ISMOBILE_SUCCESS = 'ISMOBILE_SUCCESS';

export const SCREEN_SIZE = 'SCREEN_SIZE';

export const TECHNOLOGY_SUCCESS = 'TECHNOLOGY_SUCCESS';

export const INVOLVED_SUCCESS = 'INVOLVED_SUCCESS';

export const FAQ_SUCCESS = 'FAQ_SUCCESS';

export const SECTION_LIST = 'SECTION_LIST';

